// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace FileScopedNamespace
{
    internal sealed partial class Vsix
    {
        public const string Id = "FileScopedNamespace.71b9d3ce-6eab-4163-9d1a-18c85ea13973";
        public const string Name = "File Scoped Namespace";
        public const string Description = @"With this extension, you can convert the format of your classes to a new, modern, and updated format.

";
        public const string Language = "en-US";
        public const string Version = "1.1";
        public const string Author = "SamanAzadi1996";
        public const string Tags = "Code Formatting,Formatting,File Scoped Namespace";
    }
}
